GET http://localhost:8080/users/Duw8Kxkaj2eNnbiLRyQrleq1cgECYt
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjcmlzdGkxQGNyLmNvbSIsImV4cCI6MTY0NTkwNjAwNH0.McyPhtPCERZJEJcGPgILEsP134v2EhlDcRxQRSTvfWfXuvCkVg0YoI4RpMWFs1Ob3dzkzSEbMCCO6AptT-ngGA

###
POST http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjcmlzdGkxQGNyLmNvbSIsImV4cCI6MTY0NTk5NjAzNX0._pZ4zWU2tqzLYt2b2nUoGcEv2mqhRCjkSQY-4uCj03y1Shi5dwXJyObbZfh9DRTCa_fp4EAR1MVbwmn66qg1PA

{
  "firstName": "cristian1",
  "lastName": "test",
  "email": "cristi12@cr.com",
  "password": "test"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "cristi1@cr.com",
  "password": "test"
}
###
PUT http://localhost:8080/users/Duw8Kxkaj2eNnbiLRyQrleq1cgECYt
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjcmlzdGkxQGNyLmNvbSIsImV4cCI6MTY0NTk1OTQxNH0.NxoB_zJzAq36dIRJyW7hGv_tR2dRb_tjGdPgISULnDBtKl6m2s_zkRDdzKN5w6J_jpqK2zZqLWuVqwjX64v06Q
Content-Type: application/json

{
  "firstName": "CRISTIIIIIII",
  "lastName": "Baron"
}
###
DELETE http://localhost:8080/users/Gg6ENXyXm4Ai84c75yGKh4hUbjLOQN
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjcmlzdGkxQGNyLmNvbSIsImV4cCI6MTY0NTk5NjAzNX0._pZ4zWU2tqzLYt2b2nUoGcEv2mqhRCjkSQY-4uCj03y1Shi5dwXJyObbZfh9DRTCa_fp4EAR1MVbwmn66qg1PA


###
POST http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjcmlzdGkxQGNyLmNvbSIsImV4cCI6MTY0NTA0NDQ4OH0.WnzqmTalVAEX9IBID3laevehJX7tPREdCEaLZTjCtEyHMZ4TclEpqn4a-i8XLpJOqsih2Wc0pj0ewpPaaCPVIQ
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "cristi1@cr.com",
  "password": "test"
}